apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  labels:
    release: app-service-monitor
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
  - interval: 5s